server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yomea/spring-cloud-starter.git     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:  yomea                                            # git仓库的账号
          password:  WUZHENHONg1127                                            # git仓库的密码
          
          #config-repo下有这些文件
          #neo-config-dev.properties
          #neo-config-pro.properties
          #neo-config-test.properties
          #它的http连接
          #/{application}/{profile}[/{label}]
          #/{application}-{profile}.yml
          #/{label}/{application}-{profile}.yml
          #/{application}-{profile}.properties
          #/{label}/{application}-{profile}.properties
          #例如：http://localhost:8081/neo-config/dev